<a href="https://colab.research.google.com/github/dakshesh-1293/ML_practical/blob/main/Backward_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

df=pd.read_csv("/content/drive/MyDrive/Sem-2/ML/Auto_MPG")
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [8]:
#Replace '?' With nan
df.replace('?',np.nan,inplace=True)

#Convert Horesepower to numeric
df['horsepower']=pd.to_numeric(df['horsepower'])

#drop Missing values
df=df.dropna()

#remove Non Numberic Column
if 'car name' in df.columns:
  df=df.drop(columns=['car name'])

df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
dtype: int64

In [9]:
# 2 Define Features And target
X=df.drop(columns=['mpg'])
y=df['mpg']



#train Test Split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
#


#3 Backward Feature Selection

selected_featured=list(X.columns)

#train full model First
model=LinearRegression()
model.fit(X_train[selected_featured],y_train)
y_pred=model.predict(X_test[selected_featured])
best_score=r2_score(y_test,y_pred)

print("backword Feature Elimination Process:\n")
print(f"Initial R2 score (all Features): {best_score:.4f}")

backword Feature Elimination Process:

Initial R2 score (all Features): 0.7902

In [10]:
while len(selected_featured) > 1:
    scores = []

    for feature in selected_featured:
        features_to_test = selected_featured.copy()
        features_to_test.remove(feature)

        model = LinearRegression()
        model.fit(X_train[features_to_test], y_train)

        y_pred = model.predict(X_test[features_to_test])
        score = r2_score(y_test, y_pred)

        scores.append((score, feature))   # Only once

    # Find removal that gives highest R2
    scores.sort(reverse=True)
    current_best_score, worst_feature = scores[0]

    if current_best_score >= best_score:
        best_score = current_best_score
        selected_featured.remove(worst_feature)
        print(f"Removed Feature: {worst_feature}, R2 score: {best_score:.4f}")
    else:
        break

print("\nFinal Selected Features:")
print(selected_featured)

Removed Feature: origin, R2 score: 0.7942
Removed Feature: horsepower, R2 score: 0.7944

Final Selected Features:
['cylinders', 'displacement', 'weight', 'acceleration', 'model year']