In [1]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("E:\CLG\MU\FY_2\Machine_Learning\knn_dataset.csv")

print("Dataset Preview:")
print(df.head())

Dataset Preview:
     CGPA Communication Aptitude Pro_skill Job_offered
0    High          Good     High      Good         Yes
1  Medium          Good     High      Good         Yes
2     Low           Bad      Low      Good          No
3     Low          Good      Low       Bad          No
4    High          Good     High       Bad         Yes

In [2]:
le = LabelEncoder()
     
df['CGPA'] = le.fit_transform(df['CGPA'])
df['Communication'] = le.fit_transform(df['Communication'])
df.head()

   CGPA  Communication Aptitude Pro_skill Job_offered
0     0              1     High      Good         Yes
1     2              1     High      Good         Yes
2     1              0      Low      Good          No
3     1              1      Low       Bad          No
4     0              1     High       Bad         Yes

In [3]:
df['Aptitude'] = le.fit_transform(df['Aptitude'])
df['Pro_skill'] = le.fit_transform(df['Pro_skill'])
df.head()

   CGPA  Communication  Aptitude  Pro_skill Job_offered
0     0              1         0          1         Yes
1     2              1         0          1         Yes
2     1              0         1          1          No
3     1              1         1          0          No
4     0              1         0          0         Yes

In [4]:
df['Job_offered'] = le.fit_transform(df['Job_offered'])

print("\nEncoded Dataset:")
print(df.head())

Encoded Dataset:
   CGPA  Communication  Aptitude  Pro_skill  Job_offered
0     0              1         0          1            1
1     2              1         0          1            1
2     1              0         1          1            0
3     1              1         1          0            0
4     0              1         0          0            1

In [5]:
#All Columns Except Last
X=df.iloc[:,:-1]

#LAST Column
Y=df.iloc[:,-1]

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

print("\nTraining samples:", len(X_train))

max_k = len(X_train)

for k in range(1, max_k + 1):

    print(f"K = {k}")

    classifier = KNeighborsClassifier(n_neighbors=k)

    # Train model
    classifier.fit(X_train, y_train)

    # Prediction
    y_pred = classifier.predict(X_test)

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:")
    print(cm)

    # Accuracy
    acc = accuracy_score(y_test, y_pred) * 100
    print(f"Accuracy = {acc:.2f}%")

Training samples: 14
K = 1
Confusion Matrix:
[[2 0]
 [0 2]]
Accuracy = 100.00%
K = 2
Confusion Matrix:
[[2 0]
 [0 2]]
Accuracy = 100.00%
K = 3
Confusion Matrix:
[[2 0]
 [0 2]]
Accuracy = 100.00%
K = 4
Confusion Matrix:
[[2 0]
 [1 1]]
Accuracy = 75.00%
K = 5
Confusion Matrix:
[[2 0]
 [0 2]]
Accuracy = 100.00%
K = 6
Confusion Matrix:
[[2 0]
 [2 0]]
Accuracy = 50.00%
K = 7
Confusion Matrix:
[[2 0]
 [2 0]]
Accuracy = 50.00%
K = 8
Confusion Matrix:
[[2 0]
 [2 0]]
Accuracy = 50.00%
K = 9
Confusion Matrix:
[[2 0]
 [2 0]]
Accuracy = 50.00%
K = 10
Confusion Matrix:
[[2 0]
 [2 0]]
Accuracy = 50.00%
K = 11
Confusion Matrix:
[[2 0]
 [2 0]]
Accuracy = 50.00%
K = 12
Confusion Matrix:
[[2 0]
 [2 0]]
Accuracy = 50.00%
K = 13
Confusion Matrix:
[[2 0]
 [2 0]]
Accuracy = 50.00%
K = 14
Confusion Matrix:
[[2 0]
 [2 0]]
Accuracy = 50.00%